#!/usr/bin/env bash

set -x

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_created  action="~/.config/yabai/layout.sh"
yabai -m signal --add event=space_changed  action="~/.config/yabai/layout.sh"


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.90


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   30

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Emacs" app=Emacs opacity=1
yabai -m rule --add label="iterm2" app=iTerm2 opacity=1
#yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
#yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
#yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
#yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
#yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

yabai -m rule --add app='^Mail' space=2
yabai -m rule --add title='^Whats*' space=3
yabai -m rule --add app='^Telegram' space=3
yabai -m rule --add app='^Mess*' space=3
yabai -m rule --add app=Slack space=4
yabai -m rule --add app=Signal space=4



set +x

echo "yabai configuration loaded.."
